### ISSUE TITLE
VS2013, LinkerError FileName, pbrt2obj

### ISSUE THREAD

**Issue by Chrjstoph** [ingowald/pbrt-parser#1] opened 2017-01-30 15:31 UTC
Hi, Linking fails. And I fail to find the solution.

**Comment by ingowald** [comment] 2017-01-30 17:52
Hey, Christoph,
Could you be a bit more specific? Ideally send a build log or something to go from?
For example, at a minimum the output of "make clean; make VERBOSE=1" would be useful - i just double-checked on my laptop and everything compiled and linked fine ....

**Comment by ingowald** [comment] 2017-01-30 17:56
Please note I also just pushed a new version that contains some bugfixes - nothing related to linking, though; and before pushing I had tried both my version as well as the one here on github - both worked.... so the build log would still be useful

**Comment by Chrjstoph** [comment] 2017-01-30 18:07
Hello Hingo
and thank you for your quick reply.


I added “ospray_common_EXPORTS” to the preprocessor Definitions of common.

I am rather ignorant of CMake and advanced VS stuff.

Best Regrads
Christoph

**Comment by ingowald** [comment] 2017-01-30 18:57
Outch. I'm mostly a linux user; and though most of the infrastructure should be in there to get it working on windows (all of ospcommon is from ospray, for example, which builds fine on windows) I currently have no windows machine to even built it myself to see where it's stuck. 

Windows is notoriously fickle with anything DLLs and linking (on windows you have to explicitly export every symbol you want to use; while on linux everything in a dll is visible by default); so I'm pretty sure that 99% of the problem is classes, methods, and functions in pbrt/pbrt.h that are not properly tagged with the right dll export attributes. I just defined a pbrt_parser_EXPORTS define and plugged it to all the "obvious" places; but again, I have no means of even seeing a compile output right now. If you send me a copy-n-paste of VS's error outputs I can fix them, but we'd probably need several iterations of this "you compile and send me the errors; i fix them" procedure. I'd be happy to do this, but not sure how useful that would be to you...

CMake actually helps a lot in this process - it already defines the right "<libname>_EXPORTS" flags when including the headers vs when building the DLL; but of course these "PBRT_PARSER_INTERFACE" and "OSPCOMMON_INTERFACE" macros _have_ to be added to every dll function the app is finally going to use. I've just fixed some of the naming, but again, I'd need _some_ windows output to do more than that.... :-/

**Comment by Chrjstoph** [comment] 2017-01-31 10:02
An unedited Build results in the following log.


Also: I removed following line (parsePLY, l159):

#ifdef _WIN32
//          THROW_SG_ERROR("#osp:sg:ply: gzipped file not supported yet on Windows");
#else


Christoph

**Comment by Chrjstoph** [comment] 2017-01-31 18:10
I’ve pulled your lates update, however you might want to have a look at : https://msdn.microsoft.com/de-de/library/t72ahzw1.aspx

Your members must not be declared with interface, only the structs/classes. I’ll try if it works when I remove the culprits-

**Comment by ingowald** [comment] 2017-01-31 18:13
Give me a few secs (or hours!?) ... I just added this parser to our 
ospray CI build system, which also compiles on windows. the downside is 
that I'll have to do a lot of pushes of half-ready code, because my only 
way of getting back a compile result is to push in whatever I just 
edited, and see what the CI system makes out of it.

Cheers,

Ingo

**Comment by Chrjstoph** [comment] 2017-01-31 19:23
I tried stepping your program with filename “.../pbrt-v3-scenes/simple/buddha.pbrt” but there are no tokens to parse through.

Could you give an exemplary use case?

**Comment by ingowald** [comment] 2017-01-31 19:35
pretty sure that means that it could not open the file. Just added an 
exception if that happens; the old code silently ignored that.

Are you sure, for example, about the _three_ dots at the beginning of 
the filename? If not, check your working dir. It definitely works in my 
case:

-------------------------------------------------------
parsing: /home/wald/models/pbrt-v3-scenes/simple/buddha.pbrt
Parsing PBRT World
Parsing PBRT World - done!
==> parsing successful (grammar only for now)
writing Object '<root>' : 3shps, 0insts
Done exporting to OBJ; wrote a total of 1087720 triangles

and I also just test-rendred the exported obj with ospray - no materials 
(that is expected right now), but the geometry is sound.

Cheers,

Ingo

**Comment by Chrjstoph** [comment] 2017-01-31 19:40
Those 3 dots are just to obfuscate my path and avoid confusion. So much for that :)

Materials are written.

Also, I just synced again, build your new stuff and the old problem is gone, however I removed the “PBRT_PARSER_INTERFACE” on members where necessary.

And I have a new linker error, log appended.

Good Night

**Comment by Chrjstoph** [comment] 2017-02-01 12:59
I have burrowed a little further and managed to parse the geometry of the buddha, by hard copying parsePLY.

I take it, you will rearrange that, if time permits.

Note, that you free “free(ply->elems);” in parsePLY.cpp l.363, after having closed the ply object (l.342).


The vs debugger is not happy about that.

**Comment by ingowald** [comment] 2017-02-01 18:42
My CI tests show this code now compiles and links fine on osx, centos, ubuntu, and windows; can you confirm?

**Comment by Chrjstoph** [comment] 2017-02-01 19:08
did you commit? 

latest commit was 23h ago

**Comment by ingowald** [comment] 2017-02-02 00:48
I did, but it took a bit more work today - yesterday's code DID compile under windows, but only with intel compiler.
CURRENT code also compiles with Microsoft compiler.

**Comment by Chrjstoph** [comment] 2017-02-02 07:01
It compiles smoothly. Though with a lot of warnings.

**Comment by ingowald** [comment] 2017-02-03 16:56
confirmed to work; closing this.

**Closed as completed by ingowald** 2017-02-03 16:56 UTC
